
import styles from "./page.module.css";
import Sidebar from "../components/sidebar";
import { firebase } from "../database/firebase";

export async function getServerSideProps(context) {
    const user = auth.currentUser;
    return {
        props: { user },
    };
}

export const metadata = {
    title: "BigFive",
    description: "Generated by USN/Rubynor",
  };

export default function Layout({ children }) {
  return (

    <div className={styles.flexSidebar}>
        <div className={styles.sidebar}>
            <Sidebar />
        </div>
        <div className={styles.content}>
            {children}
        </div>
    </div>

  );
}
