import React from "react";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

export const metadata = {
  title: "BigFive",
  description: "Generated by USN/Rubynor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
