import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Big Five",
  description: "Generated by create next app",
};
/**
 * @author Jørgen
 * Layout viser frem alt på nettsiden, dette er det ytre laget
 * 
 * @param {children} children
 * @returns hele nettsiden med navbar og footer og alle sider/komponenter (children)
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
